07:56:20 PM:DEBUG [connection.py:25] Conexión EXITOSA: <connection object at 0x000001A6B56D3120; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:56:20 PM:DEBUG [connection.py:38] Se abrió correctamente el cursor: <cursor object at 0x000001A6B5CE3AE0; closed: 0>
07:56:38 PM:DEBUG [logger_base.py:16] mensaje a nivel debug
07:56:38 PM:INFO [logger_base.py:17] Mensaje a nivel info
07:56:38 PM:WARNING [logger_base.py:18] Mensaje a nivel warning
07:56:38 PM:ERROR [logger_base.py:19] mensaje a nivel error
07:56:38 PM:CRITICAL [logger_base.py:20] Mensaje a nivel critical
07:59:57 PM:DEBUG [conexion.py:25] Conexión EXITOSA: <connection object at 0x000001FA18353120; dsn: 'user=postgres password=xxx dbname=product host=127.0.0.1 port=5432', closed: 0>
07:59:57 PM:DEBUG [conexion.py:38] Se abrió correctamente el cursor: <cursor object at 0x000001FA18963920; closed: 0>
08:41:15 PM:DEBUG [connection.py:25] Conexión EXITOSA: <connection object at 0x000001E84EA78E10; dsn: 'user=postgres password=xxx dbname=Cafeteria host=127.0.0.1 port=5432', closed: 0>
08:41:15 PM:DEBUG [connection.py:38] Se abrió correctamente el cursor: <cursor object at 0x000001E84EC759A0; closed: 0>
08:41:34 PM:DEBUG [logger_base.py:15] mensaje a nivel debug
08:41:34 PM:INFO [logger_base.py:16] Mensaje a nivel info
08:41:34 PM:WARNING [logger_base.py:17] Mensaje a nivel warning
08:41:34 PM:ERROR [logger_base.py:18] mensaje a nivel error
08:41:34 PM:CRITICAL [logger_base.py:19] Mensaje a nivel critical
08:41:47 PM:DEBUG [connection.py:25] Conexión EXITOSA: <connection object at 0x0000023A0BE13120; dsn: 'user=postgres password=xxx dbname=Cafeteria host=127.0.0.1 port=5432', closed: 0>
08:41:47 PM:DEBUG [connection.py:38] Se abrió correctamente el cursor: <cursor object at 0x0000023A0C423AE0; closed: 0>
09:21:12 PM:DEBUG [Connection.py:25] Conexión EXITOSA: <connection object at 0x0000016E65AB3120; dsn: 'user=postgres password=xxx dbname=Cafeteria host=127.0.0.1 port=5432', closed: 0>
09:21:12 PM:DEBUG [Connection.py:38] Se abrió correctamente el cursor: <cursor object at 0x0000016E66413920; closed: 0>
09:21:12 PM:DEBUG [product_dao.py:36] Producto Insertado: Cafe ===== ($56)
09:21:12 PM:DEBUG [product_dao.py:63] Productos insertadas: 1
09:22:10 PM:DEBUG [Connection.py:25] Conexión EXITOSA: <connection object at 0x0000016946893120; dsn: 'user=postgres password=xxx dbname=Cafeteria host=127.0.0.1 port=5432', closed: 0>
09:22:10 PM:DEBUG [Connection.py:38] Se abrió correctamente el cursor: <cursor object at 0x0000016946EA3920; closed: 0>
09:27:49 PM:DEBUG [Connection.py:25] Conexión EXITOSA: <connection object at 0x000001ADF9643120; dsn: 'user=postgres password=xxx dbname=Cafeteria host=127.0.0.1 port=5432', closed: 0>
09:27:49 PM:DEBUG [Connection.py:38] Se abrió correctamente el cursor: <cursor object at 0x000001ADF9C53920; closed: 0>
09:29:04 PM:DEBUG [Connection.py:25] Conexión EXITOSA: <connection object at 0x0000017AF9D33120; dsn: 'user=postgres password=xxx dbname=Cafeteria host=127.0.0.1 port=5432', closed: 0>
09:29:04 PM:DEBUG [Connection.py:38] Se abrió correctamente el cursor: <cursor object at 0x0000017AFA343920; closed: 0>
09:29:34 PM:DEBUG [Connection.py:25] Conexión EXITOSA: <connection object at 0x0000019ED0BA3120; dsn: 'user=postgres password=xxx dbname=Cafeteria host=127.0.0.1 port=5432', closed: 0>
09:29:34 PM:DEBUG [Connection.py:38] Se abrió correctamente el cursor: <cursor object at 0x0000019ED1533920; closed: 0>
09:34:51 PM:DEBUG [Connection.py:25] Conexión EXITOSA: <connection object at 0x0000025D45033120; dsn: 'user=postgres password=xxx dbname=Cafeteria host=127.0.0.1 port=5432', closed: 0>
09:34:51 PM:DEBUG [Connection.py:38] Se abrió correctamente el cursor: <cursor object at 0x0000025D45643920; closed: 0>
09:34:51 PM:DEBUG [product_dao.py:36] Producto Insertado: leche ===== ($56)
09:34:51 PM:DEBUG [product_dao.py:63] Productos insertadas: 1
09:36:31 PM:DEBUG [Connection.py:25] Conexión EXITOSA: <connection object at 0x000001C4E1B93120; dsn: 'user=postgres password=xxx dbname=Cafeteria host=127.0.0.1 port=5432', closed: 0>
09:36:31 PM:DEBUG [Connection.py:38] Se abrió correctamente el cursor: <cursor object at 0x000001C4E21A3920; closed: 0>
09:37:04 PM:DEBUG [Connection.py:25] Conexión EXITOSA: <connection object at 0x0000025FEFB93120; dsn: 'user=postgres password=xxx dbname=Cafeteria host=127.0.0.1 port=5432', closed: 0>
09:37:04 PM:DEBUG [Connection.py:38] Se abrió correctamente el cursor: <cursor object at 0x0000025FF01A3920; closed: 0>
09:37:04 PM:DEBUG [product_dao.py:36] Producto Insertado: Cafe ===== ($56)
09:37:04 PM:DEBUG [product_dao.py:63] Productos insertadas: 1
09:37:29 PM:DEBUG [Connection.py:25] Conexión EXITOSA: <connection object at 0x000002357DB83120; dsn: 'user=postgres password=xxx dbname=Cafeteria host=127.0.0.1 port=5432', closed: 0>
09:37:29 PM:DEBUG [Connection.py:38] Se abrió correctamente el cursor: <cursor object at 0x000002357E4E3920; closed: 0>
09:37:29 PM:DEBUG [product_dao.py:36] Producto Insertado: falopa ===== ($56)
09:37:29 PM:DEBUG [product_dao.py:63] Productos insertadas: 1
09:40:29 PM:DEBUG [Connection.py:25] Conexión EXITOSA: <connection object at 0x000002384CF23120; dsn: 'user=postgres password=xxx dbname=Cafeteria host=127.0.0.1 port=5432', closed: 0>
09:40:29 PM:DEBUG [Connection.py:38] Se abrió correctamente el cursor: <cursor object at 0x000002384D8A3920; closed: 0>
09:41:28 PM:DEBUG [Connection.py:25] Conexión EXITOSA: <connection object at 0x000001E428BE3120; dsn: 'user=postgres password=xxx dbname=Cafeteria host=127.0.0.1 port=5432', closed: 0>
09:41:28 PM:DEBUG [Connection.py:38] Se abrió correctamente el cursor: <cursor object at 0x000001E4291F3920; closed: 0>
09:41:28 PM:DEBUG [product_dao.py:88] leche ===== ($56)
09:41:28 PM:DEBUG [product_dao.py:88] Cafe ===== ($56)
09:41:28 PM:DEBUG [product_dao.py:88] falopa ===== ($56)
